version: '3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  app:
    privileged: true
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    depends_on:
      - backend